apiVersion: v1
kind: Pod
metadata:
  name: airflow-pod
spec:
  containers:
    - name: airflow
      image: bgpark82/uk-company-airflow:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow
        - name: kube-config
          mountPath: /.kube/config
          readOnly: true
        - name: minikube-profile
          mountPath: /.minikube/profiles/minikube
      env:
        - name: AIRFLOW__KUBERNETES__KUBE_CONFIG
          value: "/.kube/config"
        - name: AIRFLOW__KUBERNETES__IN_CLUSTER
          value: "False"
      command: [ "airflow", "standalone" ]
  volumes:
    - name: airflow-dags
      hostPath:
        path: /Users/byeonggilpark/Desktop/workspace/uk/visa/airflow/airflow
    - name: kube-config
      hostPath:
        path: /Users/byeonggilpark/Desktop/workspace/uk/visa/airflow/kube_config
    - name: minikube-profile
      hostPath:
        path: /Users/byeonggilpark/.minikube/profiles/minikube
        type: Directory