version: '3'

services:
  airflow:
    image: bgpark82/uk-company-airflow:latest
    networks:
      - minikube
    volumes:
      - ./airflow:/opt/airflow # dags 기본 폴더 (/opt/airflow/dags in airflow.cfg)
      - ./kube_config:/.kube/config:ro # kube_config 연결 (~/.kube/config) (ro: read only)
      - "${HOME}/.minikube:/.minikube" # cluster 접근 certificate 경로
      - ./.kube:/.kube # 외부 k8s api에 연결할 certificate 파일 경로
    environment:
      - AIRFLOW__KUBERNETES__KUBE_CONFIG=/.kube/config # airflow.cfg 설정 override하는 variable
      - AIRFLOW__KUBERNETES__IN_CLUSTER=False # airflow.cfg 설정 override하는 variable
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - REGION_NAME=${REGION_NAME}
    ports:
      - "8080:8080"
    command: airflow standalone # run all airflow component (scheduler, worker, webserver)

networks:
  minikube:
    external: true